const unusedMercList = [
    {
        id: 1,
        name: "Bulwark",
        baseHP: 100,
        baseAttack: 80,
        baseDefense: 110,
        baseSpecialAttack: 70,
        baseSpecialDefense: 105,
        baseSpeed: 70,
        currentHP: null,
        currentHPMax: null,
        currentAttack: null,
        currentDefense: null,
        currentSpecialAttack: null,
        currentSpecialDefense: null,
        currentSpeed: null,
        level: 17,
        ability: {},
        moveList: [],
    },
    {
        id: 2,
        name: "Thief",
        baseHP: 85,
        baseAttack: 90,
        baseDefense: 80,
        baseSpecialAttack: 80,
        baseSpecialDefense: 80,
        baseSpeed: 120,
        currentHP: null,
        currentAttack: null,
        currentDefense: null,
        currentSpecialAttack: null,
        currentSpecialDefense: null,
        currentSpeed: null,
        level: 50,
        ability: {},
        moveList: [],
    },
    {
        id: 3,
        name: "Marksman",
        baseHP: 80,
        baseAttack: 110,
        baseDefense: 90,
        baseSpecialAttack: 80,
        baseSpecialDefense: 85,
        baseSpeed: 90,
        currentHP: null,
        currentAttack: null,
        currentDefense: null,
        currentSpecialAttack: null,
        currentSpecialDefense: null,
        currentSpeed: null,
        level: 1,
        ability: {},
        moveList: [],
    },
    {
        id: 4,
        name: "Cleric",
        baseHP: 85,
        baseAttack: 80,
        baseDefense: 80,
        baseSpecialAttack: 100,
        baseSpecialDefense: 110,
        baseSpeed: 80,
        currentHP: null,
        currentAttack: null,
        currentDefense: null,
        currentSpecialAttack: null,
        currentSpecialDefense: null,
        currentSpeed: null,
        level: 50,
        ability: {},
        moveList: [],
    },
    {
        id: 5,
        name: "Evoker",
        baseHP: 80,
        baseAttack: 80,
        baseDefense: 70,
        baseSpecialAttack: 130,
        baseSpecialDefense: 90,
        baseSpeed: 85,
        currentHP: null,
        currentAttack: null,
        currentDefense: null,
        currentSpecialAttack: null,
        currentSpecialDefense: null,
        currentSpeed: null,
        level: 100,
        ability: {},
        moveList: [],
    },
];

const unusedMoveList = [
    {
        id: 1,
        name: "Pound",
        power: 40,
        damageType: "physical",
        effectText: "TODO",
        secondaryEffect: {
            effectName: "",
            effectChance: 30,
        },
    },
    {
        id: 2,
        name: "Slash",
        power: 40,
        damageType: "physical",
        effectText: "TODO",
        secondaryEffect: {
            effectName: "",
            effectChance: 30,
        },
    },
];

export { unusedMercList, unusedMoveList };
